- name: Initialize Kubernetes cluster
  command: kubeadm init --apiserver-advertise-address=192.168.0.120 --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
