---
- name: Setup Kubernetes Control Plane
  hosts: k8s_control
  become: yes

  roles:
    - common
    - container-runtime
    - kubernetes-install
    - control-plane-init
    - kubelet-config
    - cni-calico

