---
- name: Join Worker Nodes to Cluster
  hosts: k8s_workers
  become: yes

  roles:
    - worker-join

- name: Service CIDR Healthcheck (Post Join)
  hosts: k8s_control
  become: yes

  roles:
    - service-cidr-healthcheck
